version: '3'

services:
  caddy:
    volumes:
      - ./tools/Caddyfile.docker.dev:/etc/Caddyfile

  frontend:
    command: yarn run develop
    environment:
      HOST: frontend
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    expose:
      - 1234
      - 9222
    ports:
      - 9222:9222

  server:
    command: poetry run flask run
    environment:
      FLASK_APP: radio/api.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_PORT: 80
      FLASK_RUN_HOST: server
