version: "3"

volumes:
  db-data:
  logs:
  frontend_build:

services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./tools/Caddyfile.docker:/etc/Caddyfile
      - frontend_build:/srv
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - icecast
      - server

  icecast:
    image: moul/icecast
    restart: always
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml
    expose:
      - 8067

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - icecast.env
    expose:
      - 5432

  frontend:
    build: ./frontend
    image: frontend
    working_dir: /app
    command: yarn build
    volumes:
      - ./frontend:/app
      - frontend_build:/app/build

  server:
    build: .
    image: radio
    working_dir: /app
    command: gunicorn -b 0.0.0.0:80 radio.api:app
    volumes:
      - ./:/app
      - frontend_build:/app/frontend/build
    expose:
      - 80
    links:
      - db
    depends_on:
      - frontend
      - db
      - icecast

  stream:
    image: radio
    working_dir: /app
    command: python -m tools.stream
    volumes:
      - ./:/app
    links:
      - db
      - icecast
    depends_on:
      - frontend
      - db
      - icecast
