version: '3'

volumes:
  db-data:
  logs:
  redis-data:
  frontend_build:
  frontend_nodemodules:
    external: true

services:
  caddy:
    image: abiosoft/caddy:no-stats
    volumes:
      - ./tools/Caddyfile.docker:/etc/Caddyfile
      - frontend_build:/srv

  icecast:
    image: infiniteproject/icecast
    restart: on-failure
    volumes:
      - ./tools/fallback.mp3:/usr/share/icecast/web/fallback.mp3
      - ./tools/fallback.ogg:/usr/share/icecast/web/fallback.ogg
      - ./icecast.xml:/etc/icecast.xml
    expose:
      - 8067

  db:
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - database.env
    expose:
      - 5432

  frontend:
    image: node:12-alpine
    working_dir: /app
    command: yarn run build
    volumes:
      - ./frontend:/app
      - frontend_nodemodules:/app/node_modules
      - frontend_build:/app/dist
    environment:
      - CHOKIDAR_USEPOLLING=1

  server:
    build: .
    image: radio
    working_dir: /app
    restart: on-failure
    command: poetry run gunicorn -b 0.0.0.0:80 radio.api:app
    # logging:
    #   driver: none
    volumes:
      - ./:/app
      - frontend_build:/app/frontend/dist
    expose:
      - 80
    links:
      - db
      - redis
    depends_on:
      - db
      - icecast
      - redis

  stream:
    image: radio
    working_dir: /app
    restart: on-failure
    command: poetry run python -m radio.stream
    volumes:
      - ./:/app
    links:
      - db
      - icecast
      - redis
    depends_on:
      - db
      - icecast
      - redis
    tty: true

  redis:
    restart: on-failure
    image: redis:5
    volumes:
      - redis-data:/data
    expose:
      - 6379
