version: '3'

services:
  caddy:
    volumes:
      - ./tools/Caddyfile.docker.dev:/etc/Caddyfile
    ports:
      - "8880:80"
      - "8843:443"

  db:
    ports:
      - "5999:5432"

  frontend:
    tty: true
    stdin_open: false
    command: yarn run start
    restart: on-failure
    environment:
      HOST: frontend
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    expose:
      - 1234
      - 9222
    ports:
      - "9223:9222"

  server:
    command: poetry run flask run
    environment:
      FLASK_APP: radio/api.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_PORT: 80
      FLASK_RUN_HOST: server
