version: '3'

volumes:
  frontend_nodemodules:
    external: true

services:
  frontend-install:
    image: node:12-alpine
    volumes:
      - ./frontend/package.json:/app/package.json
      - ./frontend/yarn.lock:/app/yarn.lock
      - frontend_nodemodules:/app/node_modules
    working_dir: /app
    command: yarn install --pure-lockfile
