version: '3'

volumes:
  db-data:
  logs:
  frontend_build:
  frontend_nodemodules:
    external: true

services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./tools/Caddyfile.docker:/etc/Caddyfile
      - frontend_build:/srv
    ports:
      - 80:80
      - 443:443

  icecast:
    image: infiniteproject/icecast
    restart: always
    volumes:
      - ./icecast.xml:/etc/icecast.xml
    expose:
      - 8067
    ports:
      - 8067:8067

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - icecast.env
    expose:
      - 5432

  frontend:
    image: node:12-alpine
    working_dir: /app
    command: yarn run build
    volumes:
      - ./frontend:/app
      - frontend_nodemodules:/app/node_modules
      - frontend_build:/app/dist
    environment:
      - CHOKIDAR_USEPOLLING=1

  server:
    build: .
    image: radio
    working_dir: /app
    command: poetry run gunicorn -b 0.0.0.0:80 radio.api:app
    # logging:
    #   driver: none
    volumes:
      - ./:/app
      - frontend_build:/app/frontend/dist
    expose:
      - 80
    ports:
      - 9555:80
    links:
      - db
    depends_on:
      - frontend
      - db
      - icecast

  stream:
    image: radio
    working_dir: /app
    command: poetry run python -m radio.stream
    volumes:
      - ./:/app
    links:
      - db
      - icecast
    depends_on:
      - db
      - icecast
